/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.divesafe.application;

import java.sql.Date;
import java.time.LocalDate;
import ca.mcgill.ecse.divesafe.model.DiveSafe;
import ca.mcgill.ecse.divesafe.persistence.DiveSafePersistence;
import ca.mcgill.ecse.divesave.javafx.fxml.DiveSafeFxmlView;
import javafx.application.Application;

public class DiveSafeApplication {
  public static final boolean DARK_MODE = true;
  private static DiveSafe diveSafe;
  private static Date currentDate;
  public static void main(String[] args) {
    // Launch UI here (For Iteration 4)
    Application.launch(DiveSafeFxmlView.class, args);
  }

  public static DiveSafe getDiveSafe() {
    if (diveSafe == null) {
      // these attributes are default, you should set them later with the setters
      diveSafe = DiveSafePersistence.load();
      diveSafe = new DiveSafe(new Date(0), 0, 0);
    }
    
    return diveSafe;
  }
  public static Date getCurrentDate() {
    if (currentDate == null) {
      return Date.valueOf(LocalDate.now());
    }

    return currentDate;
  }

  public static void setCurrentDate(Date date) {
    currentDate = date;
  }

}
